const GET_REQUEST = 'GET_REQUEST';
const GET_SUCCESS = 'GET_SUCCESS';
const GET_FAIL = 'GET_FAIL';
const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNUP = 'USER_SIGNUP';
const USER_SIGNOUT = 'USER_SIGNOUT';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';
const CLEAR_CART = 'CLEAR_CART'

export { GET_FAIL, GET_SUCCESS, GET_REQUEST, USER_SIGNIN, USER_SIGNUP, USER_SIGNOUT, ADD_TO_CART, REMOVE_PRODUCT, SAVE_SHIPPING_ADDRESS, SAVE_PAYMENT_METHOD, CLEAR_CART };